import {
  Apple,
  Baby,
  Battery,
  Bed,
  Briefcase,
  BookOpen,
  Cable,
  Camera,
  Car,
  ChefHat,
  Clock,
  Contact,
  Cpu,
  Crown,
  Disc,
  Dumbbell,
  FileText,
  Flame,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  IdCard,
  Image,
  Key,
  Mail,
  PanelTop,
  PenTool,
  Pill,
  Radio,
  Receipt,
  Shirt,
  Sparkles,
  SprayCan,
  Sprout,
  Tag,
  Trash2,
  Umbrella,
  UtensilsCrossed,
  Watch,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * label (evidence.generic_category / case_decoy_categories.label) -> иконка.
 * Единая система для настоящих категорий локации и обманок — оба берут
 * иконку по одному и тому же совпадению текста, отдельного списка нет.
 */
const EVIDENCE_CATEGORY_ICONS: Record<string, LucideIcon> = {
  // Реальные категории (evidence.generic_category по всем делам/локациям)
  "Бутылки": Wine,
  "Визитки и реклама": Contact,
  "Документы и справки": FileText,
  "Еда": Apple,
  "Книги и блокноты": BookOpen,
  "Мусор": Trash2,
  "Письма и записки": Mail,
  "Средства связи": Radio,
  "Транспорт": Car,
  "Удостоверения и документы": IdCard,
  "Фотографии и видеозаписи": Camera,
  "Чеки и квитанции": Receipt,

  // Обманки (case_decoy_categories)
  "Аудио- и видеокассеты": Disc,
  "Батарейки": Battery,
  "Бытовая химия": SprayCan,
  "Головные уборы": Crown,
  "Зарядные устройства и кабели": Cable,
  "Зеркала": PanelTop,
  "Зонты": Umbrella,
  "Игрушки": Baby,
  "Инструменты": Wrench,
  "Канцелярия": PenTool,
  "Ключи и брелоки": Key,
  "Комнатные растения": Sprout,
  "Косметика и парфюмерия": Sparkles,
  "Кухонная утварь": ChefHat,
  "Лекарства и аптечка": Pill,
  "Настенные часы": Clock,
  "Настольные игры": Gamepad2,
  "Обувь": Footprints,
  "Одежда": Shirt,
  "Очки": Glasses,
  "Пепельницы и зажигалки": Flame,
  "Постельное бельё": Bed,
  "Постеры и картины": Image,
  "Посуда": UtensilsCrossed,
  "Ремни и аксессуары": Watch,
  "Спортивный инвентарь": Dumbbell,
  "Сумки и рюкзаки": Briefcase,
  "Украшения": Gem,
  "Шкатулки и сувениры": Gift,
  "Электроника": Cpu,
};

/** Категория без явного соответствия (новая обманка и т.п.) — не пустое место. */
const DEFAULT_EVIDENCE_CATEGORY_ICON: LucideIcon = Tag;

export function getEvidenceCategoryIcon(label: string): LucideIcon {
  return EVIDENCE_CATEGORY_ICONS[label] ?? DEFAULT_EVIDENCE_CATEGORY_ICON;
}
